version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing something"
      - npm i
  pre_build:
    commands:
      -
      - echo "we are in the pre build phase"
  build:
    commands:
      - npm run build
      - echo "we are in the build block"
      - echo "we will run some tests"
  post_build:
    commands:
      - echo "we are in the post build phase now"
# Include only the files required for your application to run.
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
